In [ ]:
import tensor

In [23]:
# Tensor Math & Comparison Operations

# my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                        device=device,
                        requires_grad=True
                        ) # cpu, which is the default
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [69]:
# Other common initialization methods
x = torch.empty(size = (3, 3)) # create uninitialized/empty 3x3 matrix/tensor
x = torch.zeros((3, 3)) # create 3x3 matrix with 0 vals
x = torch.rand((3, 3)) # create 3x3 matrix with vals from uniform distribution in interval 0-1
x = torch.ones((3, 3)) # create 3x3 matrix with 1 vals
x = torch.eye(5, 5) # create identity matrix # 1's on the diagoal, rest will be 0's
x = torch.arange(start=0, end=5, step=1)
x = torch.linspace(start=0.1, end=1, steps=10)
x = torch.empty(size = (1, 5)).normal_(mean=0, std=1) # std -> standard deviation
x = torch.empty(size= (1, 5)).uniform_(0, 1)
x = torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [59]:
# How to initialize and convert tensors to other types (int, float, double)
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short()) # int16
print(tensor.long()) # int64 # important / almost always used
print(tensor.half()) # float16 # not used often # newer 2000 series gpus
print(tensor.float()) # float32 # common / super important
print(tensor.double()) # float64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])


In [66]:
# Array to Tensor conversion and vice-versa
import numpy as np
np_array = np.zeros((5, 5)) # array
tensor = torch.from_numpy(np_array) # convert to tensor
np_array_back = tensor.numpy() # convert back to array