In [1]:
import torch

In [3]:
# Tensor Reshaping

x = torch.arange(9)

# similar method
x_3x3 = x.view(3, 3) # view acts on contiguous tensors meaning the tensor is stored contiguously in memory (superior)
x_3x3 = x.reshape(3, 3) # safe bet (performance loss)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [10]:
y = x_3x3.t() # tranpose the 3x3
print(y)
print(y.contiguous().view(9))
print(y.reshape(9))

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [13]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [18]:
z = x1.view(-1)
print(z.shape)

torch.Size([10])


In [22]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [26]:
z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 5, 2])


In [34]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [40]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1x1x10
print(x.shape)

torch.Size([1, 1, 10])


In [39]:
z = x.squeeze(1)
print(z.shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
