In [2]:
import torch

In [26]:
# Tensor Math & Comparison Operations

x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [38]:
# Addition (method 1)
z1 = torch.empty(3)
torch.add(x, y, out=z1)

# method 2
z2 = torch.add(x, y)

# method 3 (preferred)
z = x + y

print(z)

tensor([10, 10, 10])


In [39]:
# Subtraction
z = x - y

print(z)

tensor([-8, -6, -4])


In [40]:
# Division
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [41]:
# inplace operations
t = torch.zeros(3)
t.add_(x) # method 1
t += x # method 2
print(t)

tensor([2., 4., 6.])


In [42]:
# Exponentiation
z = x.pow(2) # method 1
z = x ** 2
print(z)

tensor([1, 4, 9])


In [43]:
# Simple comparison
z = x > 0
z = x < 0
print(z)

tensor([False, False, False])


In [44]:
# Matrix Multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2) # 2x3 # method 1
x3 = x1.mm(x2) # method 2

print(x3)

tensor([[0.9169, 1.2482, 1.0327],
        [1.3654, 1.8430, 1.9133]])


In [37]:
# Matrix Exponentiation
matrix_exp = torch.rand(5, 5)
matrix_exp.matrix_power(3)
print(matrix_exp)

tensor([[0.5002, 0.0587, 0.0763, 0.2977, 0.7417],
        [0.6744, 0.0526, 0.2461, 0.9854, 0.0228],
        [0.7678, 0.9904, 0.6016, 0.1585, 0.7438],
        [0.7009, 0.3468, 0.7319, 0.5842, 0.0259],
        [0.1555, 0.4284, 0.1220, 0.9535, 0.1116]])


In [46]:
# element wise mult.
z = x * y
print(z)

tensor([ 9, 16, 21])


In [48]:
# dot product (sum of element wise mult.)
z = torch.dot(x, y) 
print(z)

tensor(46)


In [54]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)

In [57]:
# Example of Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5)) 

# broadcasting happens to automatically expand x2 to match x1 for the subtraction to happen
z = x1 - x2 
z = x1 ** x2
print(z)

tensor([[0.8592, 0.9275, 0.8958, 0.6487, 0.9430],
        [0.7731, 0.8118, 0.8444, 0.2594, 0.3566],
        [0.4736, 0.9178, 0.7499, 0.1828, 0.9088],
        [0.8919, 0.1636, 0.0674, 0.8301, 0.8304],
        [0.9460, 0.2531, 0.4022, 0.6239, 0.7309]])
