In [2]:
import torch

In [28]:
# Tensor Indexing

batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0])

print(x[0].shape) # x[0,:]

print(x[:, 0].shape)

print(x[2, 0:10])

x[0, 0] = 100

tensor([0.1517, 0.1433, 0.9387, 0.0167, 0.7604, 0.1846, 0.0181, 0.4562, 0.6498,
        0.4427, 0.4112, 0.3511, 0.2175, 0.4050, 0.3548, 0.3604, 0.7499, 0.8708,
        0.0106, 0.2994, 0.6298, 0.9878, 0.3334, 0.1148, 0.3731])
torch.Size([25])
torch.Size([10])
tensor([0.6968, 0.5886, 0.6688, 0.3513, 0.7564, 0.2333, 0.9416, 0.8015, 0.3945,
        0.6541])


In [14]:
# Fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

tensor([2, 5, 8])


In [18]:
x = torch.rand((3, 5))
print(x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
# will pick out (1,4) 2nd row, 5th col && (0,0) 1st row, 1st col
print(x[rows, cols])
print(x[rows, cols].shape)

tensor([[0.9563, 0.7852, 0.2892, 0.9707, 0.3271],
        [0.9242, 0.3973, 0.3479, 0.5998, 0.5269],
        [0.4676, 0.0428, 0.5096, 0.4556, 0.6887]])
tensor([0.5269, 0.9563])
torch.Size([2])


In [31]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[(x < 2) & (x > 8)])
print(x[(x > 2) & (x > 8)])

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([9])


In [29]:
print(x[x.remainder(2) == 0]) # even elements (modulus)

tensor([100.])


In [34]:
# Useful operations
print(torch.where(x > 5, x, x*2)) # if x > 5, x else x*2

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [36]:
print(torch.tensor([0,0,1,2,2,3,4]).unique())

tensor([0, 1, 2, 3, 4])


In [40]:
print(x.ndimension())

1


In [41]:
print(x.numel()) # number of elements in x

10
